apiVersion: v1
kind: ServiceAccount
{% include "_meta.yaml" %}
automountServiceAccountToken: {{ automount }}
{%- if !image_pull_secrets.is_empty() %}
imagePullSecrets:
{%- for s in image_pull_secrets %}
  - name: {{ s }}
{%- endfor %}
{%- endif %}
